// Code generated by "gobinenc array.go"; DO NOT EDIT.

package array

import (
	"io"
)

func (s *Array) Write(w io.Writer) (n int, err error) {
	size := 2
	for _, v := range s.Int8Arr {
		size += 1
	}
	buf := make([]byte, size)
	offset := 0
	// Int8Arr
	buf[offset] = byte(len(s.Int8Arr))
	buf[offset+1] = byte(len(s.Int8Arr) >> 8)
	offset += 2
	for _, v := range s.Int8Arr {
		buf[offset] = byte(uint8(v))
		offset += 1
	}
	return w.Write(buf)
}
