// Code generated by "gobinenc float.go"; DO NOT EDIT.

package main

import (
	"io"
	"unsafe"
)

func (s *Float) WriteTo(w io.Writer) (n int, err error) {
	size := 12
	buf := make([]byte, size)
	offset := 0
	copy(buf[offset:], (*(*[4]byte)(unsafe.Pointer(&(s.Float32))))[:])
	offset += 4
	copy(buf[offset:], (*(*[8]byte)(unsafe.Pointer(&(s.Float64))))[:])
	offset += 8
	return w.Write(buf)
}

func (s *Float) ReadFrom(r io.Reader) error {
	r.Read((*(*[4]byte)(unsafe.Pointer(&(s.Float32))))[:])
	r.Read((*(*[8]byte)(unsafe.Pointer(&(s.Float64))))[:])
	return nil
}
