// Code generated by "gobinenc testdata/complex.go"; DO NOT EDIT.

package main

import (
	"io"
	"unsafe"
)

func (s *Complex) Write(w io.Writer) (n int, err error) {
	size := 24
	buf := make([]byte, size)
	offset := 0
	copy(buf[offset:], (*(*[8]byte)(unsafe.Pointer(&(s.Complex64))))[:])
	offset += 8
	copy(buf[offset:], (*(*[16]byte)(unsafe.Pointer(&(s.Complex128))))[:])
	offset += 16
	return w.Write(buf)
}

func (s *Complex) Read(r io.Reader) error {
	r.Read((*(*[8]byte)(unsafe.Pointer(&(s.Complex64))))[:])
	r.Read((*(*[16]byte)(unsafe.Pointer(&(s.Complex128))))[:])
	return nil
}
