// Code generated by "gobinenc slice.go"; DO NOT EDIT.

package slice

import (
	"io"
)

func (s *Slice) Write(w io.Writer) (n int, err error) {
	size := 2
	size += 1 * len(s.Int8Slice)
	buf := make([]byte, size)
	offset := 0
	// Int8Slice
	buf[offset] = byte(len(s.Int8Slice))
	buf[offset+1] = byte(len(s.Int8Slice) >> 8)
	offset += 2
	for _, v := range s.Int8Slice {
		buf[offset] = byte(uint8(v))
		offset += 1
	}
	return w.Write(buf)
}
