// Code generated by "gobinenc string.go"; DO NOT EDIT.

package string

import (
	"io"
)

func (s *String) Write(w io.Writer) (n int, err error) {
	size := 2
	size += len(s.S)
	buf := make([]byte, size)
	offset := 0
	// S
	buf[offset] = byte(len(s.S))
	buf[offset+1] = byte(len(s.S) >> 8)
	offset += 2
	copy(buf[offset:], s.S)
	offset += len(s.S)
	return w.Write(buf)
}
